apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic4-yq6s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic4-yq6s
    app.kubernetes.io/part-of: jan7-forked
  name: devfile-sample-python-basic4-yq6s
  namespace: mreid1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-python-basic4-yq6s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-python-basic4-yq6s
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:2d4ee255622a5dcf59bf8a9da3744aacd64f981456a048fc6f9559a5270e26ea
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
